### ISSUE TITLE
Implement the component for Company card for list items according to the mockups on figma

### ISSUE THREAD

**Issue by VovaD199** [ita-social-projects/Forum#173]
Tasks for the front end. Explore creating cards for list items according to the mockups on figma

https://www.figma.com/file/gMu88CJcuaJSSoTGC5ZYfD/Forum?type=design&node-id=1788-13571&mode=design&t=s21pv44c0lNTs1BS-4

**Comment by Shushunya** [comment]
Implemented long with #247
