### ISSUE TITLE
refactor model names

### ISSUE THREAD

**Issue by ddianaoo** [ita-social-projects/Forum#204]
Rename model fields:

CustomUser:
(remove person prefix)
- [x] person_email -> email
- [x] person_name -> name
- [x] person_surname -> surname

Activity:

- [x]  activity_id -> id

Category:

- [x]  category_id -> id

Profile:

- [x] profile_id -> id
- [x] remove `comp_` prefix

**Comment by Shushunya** [comment]
Clarify: 

1. Use `user` or `person` naming for the person who signups and linked to the profile.
2. comp_registered -> 

- rename to `is_registered`
- remove it completely, use `is_startup` Boolean as a flag, which default value is set to False. So by default profile is a registered company.

**Comment by Shushunya** [comment]
Clarify 3:
Do we need to explicitly set id field in models? -> `id = models.AutoField(primary_key=True)`
