### ISSUE TITLE
[Profile] Expand text blocks for detailed information

### ISSUE THREAD

**Issue by mehalyna** [ita-social-projects/Forum#306]
#299 

The profile page contains text blocks that can be expanded for detailed information.
Task
1. The text block is filled with the leading part of the full information (appr. 6 rows).
2. The leading part has to be cut to the end of the previous sentence ('.' character) or to the context of the sentence (e.g. ',' character) in such a way that the content of the text does not cause ambiguous interpretation or prohibited content.
3. The leading part should be completed with "Читати далі" link.
4. The click on "Читати далі" would provide the view of all the text.
5. The expanded state is not stored. The next time the user opens the page, it will be collapsed again.

**Comment by Lvyshnevska** [comment]
Second point wasn't implemented as AntDesign doesn't provide such functionality.
