### ISSUE TITLE
[Profile] The text about the kind of changes doesn't correspond to the active tab on the editing profile page

### ISSUE THREAD

**Issue by mehalyna** [ita-social-projects/Forum#380]
![Image](https://github.com/ita-social-projects/Forum/assets/39273210/dedcea13-37d8-42ea-a2b0-af941676642d)

**Comment by oksanahorishna** [comment]
The sub-header should be as follows:
1, **"Інформація про користувача платформи"** for "Інформація про користувача" section
2. **"Інформація про компанію"** for "Загальна інформація", "Контакти", "Інформація про товари/послуги", "Додаткова інформація", 
3. **"Інформація про стартап"** for "Стартап" section
