### ISSUE TITLE
Investigate the ability to restore password

### ISSUE THREAD

**Issue by mehalyna** [ita-social-projects/Forum#39]

**Comment by whooaami** [comment]
**Presentation**
https://docs.google.com/presentation/d/16703G0F81nVzJn45jV_1PR-23JUzTqlu/edit?usp=sharing&ouid=101353231253298094333&rtpof=true&sd=true

**Documentation**
DRF Authentication https://www.django-rest-framework.org/api-guide/authentication/
Djoser’s documentation https://djoser.readthedocs.io/en/latest/
Djoser GitHub https://github.com/sunscrapers/djoser
DRF Reset Password example https://morioh.com/a/fe0e3a395d8b/authenticate-with-djoser
