### ISSUE TITLE
[Profile] an extra 'Delete Account' window appears after clicking the 'Delete Profile' button

### ISSUE THREAD

**Issue by Olha-231119** [ita-social-projects/Forum#430]
**Environment**:  OS Windows 11 Home, Google Chrome.
**Reproducible**:  always.
**Build found**: [#68](https://github.com/ita-social-projects/Forum/issues/68)
**Linked epic**: [#6 ](https://github.com/ita-social-projects/Forum/issues/3)

**Steps to reproduc**e:_

1.Navigate to http://178.212.110.52/  
2. The user logged in as a registered member
3. The 'Профіль' page is open
4. The 'Загальна інформація' tab is open.                                                                                                                                                         5.Click on 'Видалити профіль' tab

 
**Actual result**:

An extra "Видалити аккаунт" window appears

**Expected result**:

A modal window appears "Ви впевнені, що хочете видалити профіль?"

**Postcondition** :

The user is redirected to the "Головна" page.

**User story and test case links**:

[User story: #68](https://github.com/ita-social-projects/Forum/issues/68)
[[Test case]]https://(https://jira.softserve.academy/browse/FOR-61))(https://jira.softserve.academy/browse/FOR-61)

 **Labels to be added**:
![Defect 130 к user story 68](https://github.com/ita-social-projects/Forum/assets/151424095/9d118747-c8b5-4e7a-8304-3417f6334789)
Priority: Low
Severity : Minor
Type : Functional

**Comment by mehalyna** [comment]
implemented according to design
