### ISSUE TITLE
[Registration] No Registration when the password with more than 20 symbols is created

### ISSUE THREAD

**Issue by eexampleman196** [ita-social-projects/Forum#559]
**Environment:** Windows 10, Browser Chrome, Version 122.0.6261.96.
**Reproducible:** always

**Preconditions**
Move to http://178.212.110.52/

**Steps to reproduce**
1. Go to the registration page
2. Fill in all the registration fields, create a password with more than 20 symbols, but less than 50 symbols

**Actual result**
There is an error message "Пароль не відповідає вимогам" and user can't continue a registration

**Expected result**
The modal window is appeared

**User story and test case links**
User story #
Test case #558  

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: medium"), Type ("Functional").

**Comment by ohorodnykostap** [comment]
Link on story [#592](https://github.com/ita-social-projects/Forum/issues/592)
