### ISSUE TITLE
[Profile Moderation] Add icon on the banner/logo if profile is in 'Pending Moderation' status

### ISSUE THREAD

**Issue by MissMS** [ita-social-projects/Forum#625]
As a profile owner, I want to see the icon on the fields under moderation so I clearly understand when my changes are visible for all users

**Acceptance criteria:**

1. IF profile status = '_Pending Moderation'_ THEN show the icon on the banner and/or logo (depending on which field was updated)
2. Show the tooltip by hovering on '_Pending Moderation'_ icon:
  2.1. *Статус модерації:* Очікується
  2.2. *Час відправки запиту:* <dd.MM.yyyy hh:mm> 

**Affected Areas:**
    - Main Page, if company is shown there
    - Companies List
    - Company Profile (View mode)
    - Company Profile (Edit mode)

**DESIGN:** https://www.figma.com/design/gMu88CJcuaJSSoTGC5ZYfD/Forum?node-id=4936-69617
**EPIC**: #615

**Comment by alona-ruda** [comment]
Actual design: tooltip on both - banner and logo

![Image](https://github.com/user-attachments/assets/efbc7c54-edc3-4543-b890-cfe64c2a92e0)
