### ISSUE TITLE
Create search functionality

### ISSUE THREAD

**Issue by VovaD199** [ita-social-projects/Forum#80]
#22 exclude validation of empty search field

**Comment by mojoym** [comment]
Scenario 1: Searching by Company Name with Exact Match
When I enter a valid company name "Сільпо" in the search bar
And I click on the search button
Then the system display a list of companies with an exact match for "Сільпо"
And the results sorted in alphabetical order by company name
And the list should include companies with an exact match to the search term "Сільпо"

Yesterday added some changes to this task:
And the counter should show how many search results were found
I didn't add this thing yet

Scenario 2: Searching by Partial Company Name
When I enter a partial company name "Сіль" in the search bar
The system display a list of companies that contain the partial term "Сіль" in their name
And the results sorted in alphabetical order by company name
And the list only include companies with names containing the partial term "Сіль"

Yesterday added some changes to this task:
And the counter should show how many search results were found
I didn't add this thing yet

Scenario 3: Empty Search Input
Given I am on the main page
When I leave the search bar empty
And I click on the search button
Then the system does nothing_**

This Scenario edited yesterday, I didn't change this thing yet from previous scenario

Scenario 4: No Search Results
Given I am on the main page
When I enter a valid company name "Samsung" in the search bar
And I click on the search button
Then the system should display a message indicating that there are no companies matching the search term "Samsung."
And the counter should show 0 search results

This Scenario edited yesterday, I didn't change this thing yet from previous scenario

Scenario 5: Case Insensitive Search
When I enter a company name "Сільпо" in the search bar, with different letter cases (e.g., "сільпо" or "СІЛЬПО")
The system treat the search as case-insensitive and display results for "Сільпо" regardless of letter case
And the results sorted in alphabetical order by company name
And the list only include companies with names matching "Сільпо" in any letter case.

Yesterday added some changes to this task:
And the counter should show how many search results were found
I didn't add this thing yet

**Comment by VovaD199** [comment]
#156
