### ISSUE TITLE
[Redesign] Log In Page

### ISSUE THREAD

**Issue by Lvyshnevska** [ita-social-projects/Forum#841]
**As a** User,  
**I want to** log into the platform seamlessly with clear and intuitive visual feedback,  
**So that** I can access my account quickly and correct any errors if needed.  

---

#### Acceptance Criteria:

1. **Log In Page Layout:**
   - A centered login form with fields for:
     - **Email Address**: Input field with a placeholder ("Введіть свою електронну пошту").
     - **Password**: Password input with an eye icon to toggle password visibility.
   - Buttons for:
     - **Forgot Password?**: A link to password recovery.
     - **Log In**: Primary button labeled "Увійти".
     - **Sign Up Option**: Below the form, a message: "Вперше на нашому сайті? Зареєструйтесь".

2. **Form Validations:**
   - **Email Format Validation**: If the email is invalid, display an error in red: 
     - _"Введіть адресу електронної пошти у форматі name@example.com"_.
   - **Password Error Handling**: If credentials are incorrect:
     - **Error Message in Red**: _"Електронна пошта чи пароль вказані некоректно"_.  
   - The error messages should appear dynamically without a page reload.

3. **Visual Feedback for Errors:**
   - Highlight the error field in **red borders** when the user enters incorrect data.
   - Password error feedback shows when typing invalid input (mockup shows real-time error detection).

4. **Password Toggle Feature:**
   - Clicking the eye icon will toggle the password visibility on and off.

5. **Mobile and Desktop Views:**
   - The layout must be responsive:
     - On **desktop**, the form remains centered.
     - On **mobile**, the form should adjust its size and position to remain user-friendly.

6. **Footer and Header Consistency:**
   - Header navigation includes links for "Про нас", "Підприємства та сектори", "Пошук", "Увійти", and "Зареєструватися".
   - Footer must remain visible with:
     - Contact information and categories for "Підприємства" and "Сектори".
     - Links for "Політика конфіденційності" and "Умови користування".

7. **Error Handling and Retry Option:**
   - If login fails multiple times, users can retry:
     - The system should guide users to click "Забули пароль?" if they need recovery.

8. **User Redirection:**
   - Upon successful login, users are redirected to the main page.
  
---
**Mockups**
![image](https://github.com/user-attachments/assets/f9a70afd-2a38-48d8-93c0-10d852cdfa75)

![image](https://github.com/user-attachments/assets/dbecf5bd-dc06-4dd2-ab2d-d257e6cc0837)

![image](https://github.com/user-attachments/assets/d38cb81a-8db8-49f7-8f94-3cc3c71c145c)

![image](https://github.com/user-attachments/assets/8ca7d744-b02c-40a5-8e3f-c6edad57d271)

Link to Mockup
https://www.figma.com/design/pdh0xc92SJqnUmix7dkeRT/Forum-Project-(New)?node-id=2028-17451&node-type=frame&t=keEWVY8UaeXRuy3C-0

Epic #844

**Comment by parsival2022** [comment]
I think everything looks like it should be.
