### ISSUE TITLE
[Admin] Filter Users by Status (Multi-Optional Dropdown)

### ISSUE THREAD

**Issue by mehalyna** [ita-social-projects/Forum#983]
**As an** Admin,  
**I want to** filter users by multiple statuses using a multi-optional dropdown,  
**So that** I can easily manage users based on their role or current state in the system.  

---

#### **Multi-Optional Dropdown for Status:**
1. A multi-select dropdown is provided in the **Статус (Status)** column header.
2. The dropdown contains the following options:
   - **Активний (Active)**
   - **Адмін (Admin)**
   - **СуперЮзер (SuperUser)**
   - **Видалений (Deleted)**

#### **Filtering by Status:**
1. The admin can select one or multiple statuses from the dropdown.
2. The list dynamically updates to display users that match any of the selected statuses.
3. If no statuses are selected, the list shows all users.

#### **Visual Feedback:**
1. Each selected status in the dropdown is visually indicated with a checkmark.
2. A "clear" option allows the admin to deselect all statuses at once.

#### **Combined Filters:**
1. The status filter can be used in combination with other filters, such as:
   - **Прізвище та ім'я (Last Name and First Name)**
   - **Email**
2. Results dynamically update based on the combined filter criteria.

---

### **UI/UX Notes:**
- The dropdown maintains a user-friendly interface with hover and click states.
- Ensure accessibility with keyboard navigation and screen reader compatibility.
- Responsive design: dropdown should work seamlessly across all screen sizes.

--- 

### **Error Handling:**
1. If the dropdown fails to load, show an appropriate error message (e.g., *"Unable to load statuses. Please try again later."*).
2. If the list update fails, display a fallback message like *"Filtering failed. Please refresh the page."*.  

---

Mockup

![image](https://github.com/user-attachments/assets/31a38d0c-5e93-4320-90bb-fe683d31fc55)

**Epic link** #821

**Comment by Andrewakiv** [comment]
![Image](https://github.com/user-attachments/assets/c095789b-b1ba-4afe-b3e1-22e16e795a45)
![Image](https://github.com/user-attachments/assets/0f7cf769-e7db-42df-aef4-03f8990aa06d)
![Image](https://github.com/user-attachments/assets/7dff2721-a505-4cc7-b187-f5d13b7dc76c)
