### ISSUE TITLE
[Admin] Company Statistics Page

### ISSUE THREAD

**Issue by mehalyna** [ita-social-projects/Forum#999]
**As an Administrator**,  
**I want to** view analytical data about companies on a dedicated page,  
**So that** I can quickly access up-to-date statistics to monitor platform activity.

---

### **Acceptance Criteria:**

1. **"Company Statistics" Section**:  
   - Displayed in the left-side menu of the admin panel.  
   - The active section is highlighted in bold when selected.  
   - The page includes a title: **"Company Statistics"**.

2. **Key Metrics Display**:  
   - Analytical data is displayed in a structured table or as separate blocks.  
   - Metrics include:
     - **Total Registered Companies**.  
     - **Total Startups**.  
     - **Total Investors**.  
     - **Total Blocked Companies**.

3. **Dynamic Data Updates**:  
   - Metrics are automatically retrieved and updated from the database.  
   - Data always reflects the latest platform state.

4. **Responsive Design**:  
   - The page layout is fully responsive, ensuring proper display on different screen sizes.

---

### **Validation Rules:**
1. Metrics must display accurate numerical values.  
2. Data refreshes dynamically on page load or real-time updates.  
3. If no data is available for any metric, the system displays:  
   **"No data available"** under the respective category.

---
Mockup:

![image](https://github.com/user-attachments/assets/39b337c8-10e6-404a-9b25-3e940ba60c91)

**Comment by Andrewakiv** [comment]
![Image](https://github.com/user-attachments/assets/677a0934-6550-4aa6-9d84-81b466d11ca6)
